# Generated by Django 5.2.13 on 2026-04-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('quiz', 'Quiz'), ('homework', 'Homework'), ('project', 'Project')], default='exam', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
